export const GAME_CORE_VERSION = "1.5.0-r6.m15.sync";

export * from "./ai";
export * from "./cards";
export * from "./claims";
export * from "./engine";
export * from "./errors";
export * from "./factories";
export * from "./formations";
export * from "./invariants";
export * from "./random";
export * from "./replay";
export * from "./report";
export * from "./review";
export * from "./room";
export * from "./projection";
export * from "./protocol";
export * from "./simulation";
export * from "./tactics";
export * from "./victory";
export type * from "./types";
